# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9.1
      #- image: circleci/postgres:9.4

    working_directory: /go/src/github.com/stitchfix/go-postgres-testdb
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: wget https://www.openscg.com/bigsql/oscg_download?file=packages/postgresql-9.6.5-1-x64-bigsql.deb -o /tmp/postgresql.deb
      - run: sudo dpkg -i /tmp/postgresql.deb
      - run: go get -v -t -d ./...
      - run: go get github.com/kardianos/govendor
      - run: govendor sync
      - run: go test -v ./...